"""
Aureon™ — FastAPI Application
Platform: aureon v0.1.0
Domain: federal_procurement

Auto-generated by Zuup Forge. Domain logic goes in services/.
"""

from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from forge.substrate.zuup_audit.middleware import AuditMiddleware
from forge.substrate.zuup_observe.tracing import setup_tracing
from forge.substrate.zuup_observe.health import health_router
from forge.substrate.zuup_gateway.rate_limit import RateLimitMiddleware
from forge.substrate.zuup_gateway.versioning import VersionMiddleware

from platforms.aureon.routes import router as api_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifecycle: startup and shutdown."""
    # Startup
    setup_tracing(service_name="aureon")
    # TODO: Initialize database connections, caches, model loading
    yield
    # Shutdown
    # TODO: Clean up connections


app = FastAPI(
    title="Aureon™",
    description="Planetary-Scale Procurement Substrate",
    version="0.1.0",
    lifespan=lifespan,
    docs_url="/docs" if True else None,
    redoc_url="/redoc" if True else None,
)

# Middleware (order matters: outermost first)
app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(RateLimitMiddleware, rate="500/min")
app.add_middleware(AuditMiddleware, platform="aureon")
app.add_middleware(VersionMiddleware, current_version="v1")

# Routes
app.include_router(api_router)
app.include_router(health_router)
