-- Zuup Forge: Auto-generated migration for Aureon™
-- Platform: aureon v0.1.0
-- Generated by forge compiler

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- Audit chain for aureon
CREATE TABLE IF NOT EXISTS aureon_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    platform VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    principal_id VARCHAR(255) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    prev_hash VARCHAR(64),
    metadata JSONB DEFAULT '{}'
);
CREATE INDEX idx_aureon_audit_entity ON aureon_audit(entity_type, entity_id);
CREATE INDEX idx_aureon_audit_time ON aureon_audit(timestamp DESC);

-- Entity: Opportunity
-- A federal contracting opportunity from SAM.gov
CREATE TABLE IF NOT EXISTS aureon_opportunity (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    notice_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    agency VARCHAR(255) NOT NULL,
    sub_agency VARCHAR(255),
    naics_codes TEXT[] NOT NULL,
    set_asides TEXT[] NOT NULL,
    response_deadline TIMESTAMPTZ DEFAULT NOW(),
    estimated_value NUMERIC(18,4) NOT NULL,
    place_of_performance VARCHAR(255),
    solicitation_type VARCHAR(255) NOT NULL,
    full_text TEXT NOT NULL,
    embedding vector(768) NOT NULL,
    source_url VARCHAR(255) NOT NULL
);

CREATE INDEX idx_aureon_opportunity_notice_id ON aureon_opportunity(notice_id);
CREATE INDEX idx_aureon_opportunity_title_search ON aureon_opportunity USING gin(to_tsvector('english', title));
CREATE INDEX idx_aureon_opportunity_agency ON aureon_opportunity(agency);
CREATE INDEX idx_aureon_opportunity_full_text_search ON aureon_opportunity USING gin(to_tsvector('english', full_text));
CREATE INDEX idx_aureon_opportunity_embedding_vec ON aureon_opportunity USING ivfflat(embedding vector_cosine_ops) WITH (lists = 100);

-- Entity: Vendor
-- A potential contractor/vendor
CREATE TABLE IF NOT EXISTS aureon_vendor (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    cage_code VARCHAR(255) UNIQUE NOT NULL,
    uei VARCHAR(255) UNIQUE NOT NULL,
    legal_name VARCHAR(255) NOT NULL,
    dba_name VARCHAR(255),
    capabilities TEXT[] NOT NULL,
    naics_codes TEXT[] NOT NULL,
    certifications TEXT[] NOT NULL,
    past_performance_score DOUBLE PRECISION,
    sam_status VARCHAR(255) NOT NULL,
    contact_email VARCHAR(255) NOT NULL -- ENCRYPTED (app-level AES-256-GCM),
    hubzone_qualified BOOLEAN DEFAULT FALSE,
    capability_embedding vector(768) NOT NULL
);

CREATE INDEX idx_aureon_vendor_legal_name_search ON aureon_vendor USING gin(to_tsvector('english', legal_name));
CREATE INDEX idx_aureon_vendor_dba_name_search ON aureon_vendor USING gin(to_tsvector('english', dba_name));
CREATE INDEX idx_aureon_vendor_capabilities_search ON aureon_vendor USING gin(to_tsvector('english', capabilities));
CREATE INDEX idx_aureon_vendor_capability_embedding_vec ON aureon_vendor USING ivfflat(capability_embedding vector_cosine_ops) WITH (lists = 100);

-- Entity: OpportunityMatch
-- AI-scored match between opportunity and vendor
CREATE TABLE IF NOT EXISTS aureon_opportunitymatch (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    match_score DOUBLE PRECISION NOT NULL,
    capability_score DOUBLE PRECISION NOT NULL,
    compliance_score DOUBLE PRECISION NOT NULL,
    past_performance_score DOUBLE PRECISION NOT NULL,
    set_aside_eligible BOOLEAN DEFAULT FALSE,
    explanation TEXT NOT NULL,
    model_version VARCHAR(255) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL
);


-- Junction: Opportunity <-> Vendor
CREATE TABLE IF NOT EXISTS aureon_opportunitymatch (
    opportunity_id UUID REFERENCES aureon_opportunity(id),
    vendor_id UUID REFERENCES aureon_vendor(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB DEFAULT '{}',
    PRIMARY KEY (opportunity_id, vendor_id)
);

-- RETENTION POLICY: Audit records retained for 2555 days
-- Implement via pg_cron or application-level cleanup

-- Auto-update updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_aureon_opportunity_updated_at
    BEFORE UPDATE ON aureon_opportunity
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_aureon_vendor_updated_at
    BEFORE UPDATE ON aureon_vendor
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_aureon_opportunitymatch_updated_at
    BEFORE UPDATE ON aureon_opportunitymatch
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
